name: CI

on:
  # manual dispatch
  workflow_dispatch:
  # run on PRs to master when - is opened,
  # new commit is pushed or is set as ready for review
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-20.04
    # disable run if the PR is draft (as our CLI creates PR as draft once the issue is in progress)
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Execute Detekt
        run: |
          cd backend
          ./gradlew detekt

      - name: Execute Unit tests
        run: |
          cd backend
          ./gradlew test
